vich_uploader:
    db_driver: orm

    mappings:
        user_image:
            uri_prefix: /media/user
            upload_destination: '%kernel.project_dir%/public/media'
            # Will rename uploaded files using a uniqueid as a prefix.
            namer: Vich\UploaderBundle\Naming\OrignameNamer