controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

api_auth_login:
    path: /api/auth/login
    methods: ['POST']

api_refresh_token:
  path: /api/auth/refresh    
  controller: gesdinet.jwtrefreshtoken::refresh
